### ISSUE TITLE
Doesn't enforce divergence

### ISSUE THREAD

**Issue by CAD97** [pierzchalski/let_match_macro#1]
Will need to change
https://github.com/pierzchalski/let_match_macro/blob/ebbdd09fdbd5ec98be49542ac3613db8d96a59fb/let_match_macro/src/lib.rs#L51
into something along the lines of
```rust
    #(#arm_pat => {
        let _: ! = #arm_expr;
    })*
```

**Comment by pierzchalski** [comment]
Fixed in [620a764](https://github.com/pierzchalski/let_match_macro/commit/620a76493600a126abda09b2e54a23fe81d69b05).
